import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class AppTheme{
  static ThemeData appTheme() {
    return ThemeData(
      applyElevationOverlayColor: false,
      brightness: Brightness.light,
      buttonTheme: ButtonThemeData(
        alignedDropdown: false,
        colorScheme: ColorScheme(
          brightness: Brightness.light,
          primary: const Color(0xFFE9967E),
          onPrimary: Colors.white,
          primaryContainer: const Color(0xFFFFDBD1),
          onPrimaryContainer: const Color(0xFF3B0A00),
          secondary: const Color(0xFF77574E),
          onSecondary: Colors.white,
          secondaryContainer: const Color(0xFFFFDBD1),
          onSecondaryContainer: const Color(0xFF2C150F),
          tertiary: const Color(0xFF6C5D2F),
          onTertiary: Colors.white,
          tertiaryContainer: const Color(0xFFF5E1A7),
          onTertiaryContainer: const Color(0xFF231B00),
          error: const Color(0xFFBA1A1A),
          onError: Colors.white,
          errorContainer: const Color(0xFFFFDAD6),
          onErrorContainer: const Color(0xFF410002),
          background: const Color(0xFFFFF8F6),
          onBackground: const Color(0xFF231917),
          surface: const Color(0xFFFFF8F6),
          onSurface: const Color(0xFF231917),
          surfaceVariant: const Color(0xFFFCEAE5),
          onSurfaceVariant: const Color(0xFF53433F),
          outline: const Color(0xFF85736E),
          inverseSurface: const Color(0xFF392E2B),
          onInverseSurface: const Color(0xFFFFEDE8),
          inversePrimary: const Color(0xFFFFB5A0),
          shadow: Colors.black,
        ),
        height: 36,
        layoutBehavior: ButtonBarLayoutBehavior.padded,
        minWidth: 88,
        padding: const EdgeInsets.symmetric(horizontal: 16),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(2),
          side: BorderSide.none,
        ),
        textTheme: ButtonTextTheme.normal,
      ),
      canvasColor: const Color(0xFFFFF8F6),
      cardColor: const Color(0xFFFFF8F6),
      colorScheme: ColorScheme.light(
        primary: const Color(0xFFE9967E),
        onPrimary: Colors.white,
        primaryContainer: const Color(0xFFFFDBD1),
        onPrimaryContainer: const Color(0xFF3B0A00),
        secondary: const Color(0xFF77574E),
        onSecondary: Colors.white,
        secondaryContainer: const Color(0xFFFFDBD1),
        onSecondaryContainer: const Color(0xFF2C150F),
        tertiary: const Color(0xFF6C5D2F),
        onTertiary: Colors.white,
        tertiaryContainer: const Color(0xFFF5E1A7),
        onTertiaryContainer: const Color(0xFF231B00),
        error: const Color(0xFFBA1A1A),
        onError: Colors.white,
        errorContainer: const Color(0xFFFFDAD6),
        onErrorContainer: const Color(0xFF410002),
        background: const Color(0xFFFFF8F6),
        onBackground: const Color(0xFF231917),
        surface: const Color(0xFFFFF8F6),
        onSurface: const Color(0xFF231917),
        surfaceVariant: const Color(0xFFFCEAE5),
        onSurfaceVariant: const Color(0xFF53433F),
        outline: const Color(0xFF85736E),
        inverseSurface: const Color(0xFF392E2B),
        onInverseSurface: const Color(0xFFFFEDE8),
        inversePrimary: const Color(0xFFFFB5A0),
        shadow: Colors.black,
      ),
      disabledColor: const Color(0x61000000),
      dividerColor: const Color(0x1F231917),
      focusColor: const Color(0x1F000000),
      highlightColor: const Color(0x66BCBCBC),
      hintColor: const Color(0x99000000),
      hoverColor: const Color(0x0A000000),
      iconTheme: IconThemeData(
        color: const Color(0xDD000000),
      ),
      indicatorColor: Colors.white,
      inputDecorationTheme: InputDecorationTheme(
        alignLabelWithHint: false,
        filled: false,
        floatingLabelAlignment: FloatingLabelAlignment.start,
        floatingLabelBehavior: FloatingLabelBehavior.auto,
        isCollapsed: false,
        isDense: false,
      ),
      materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
      platform: TargetPlatform.windows,
      primaryColor: const Color(0xFFE9967E),
      primaryColorDark: const Color(0xFF1976D2),
      primaryColorLight: const Color(0xFFBBDEFB),
      primaryIconTheme: IconThemeData(
        color: Colors.black,
      ),
      textTheme: GoogleFonts.aBeeZeeTextTheme().copyWith(
        bodyLarge: GoogleFonts.aBeeZee(
          fontSize: 16,
          fontWeight: FontWeight.w400,
          color: const Color(0xFF191C20),
        ),
        bodyMedium: GoogleFonts.aBeeZee(
          fontSize: 14,
          fontWeight: FontWeight.w400,
          color: const Color(0xFF191C20),
        ),
        bodySmall: GoogleFonts.aBeeZee(
          fontSize: 12,
          fontWeight: FontWeight.w400,
          color: const Color(0xFF191C20),
        ),
        titleLarge: GoogleFonts.aBeeZee(
          fontSize: 20,
          fontWeight: FontWeight.w500,
          color: const Color(0xFF191C20),
        ),
        titleMedium: GoogleFonts.aBeeZee(
          fontSize: 16,
          fontWeight: FontWeight.w400,
          color: const Color(0xFF191C20),
        ),
        titleSmall: GoogleFonts.aBeeZee(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          color: const Color(0xFF191C20),
        ),
        headlineLarge: GoogleFonts.aBeeZee(
          fontSize: 40,
          fontWeight: FontWeight.w400,
          color: const Color(0xFF191C20),
        ),
        headlineMedium: GoogleFonts.aBeeZee(
          fontSize: 34,
          fontWeight: FontWeight.w400,
          color: const Color(0xFF191C20),
        ),
        headlineSmall: GoogleFonts.aBeeZee(
          fontSize: 24,
          fontWeight: FontWeight.w400,
          color: const Color(0xFF191C20),
        ),
        labelLarge: GoogleFonts.aBeeZee(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          color: const Color(0xFF191C20),
        ),
        labelMedium: GoogleFonts.aBeeZee(
          fontSize: 11,
          fontWeight: FontWeight.w400,
          color: const Color(0xFF191C20),
        ),
        labelSmall: GoogleFonts.aBeeZee(
          fontSize: 10,
          fontWeight: FontWeight.w400,
          color: const Color(0xFF191C20),
        ),
        displayLarge: GoogleFonts.aBeeZee(
          fontSize: 96,
          fontWeight: FontWeight.w300,
          color: const Color(0xFF191C20),
        ),
        displayMedium: GoogleFonts.aBeeZee(
          fontSize: 60,
          fontWeight: FontWeight.w300,
          color: const Color(0xFF191C20),
        ),
        displaySmall: GoogleFonts.aBeeZee(
          fontSize: 48,
          fontWeight: FontWeight.w400,
          color: const Color(0xFF191C20),
        ),
      ),
      scaffoldBackgroundColor: const Color(0xFFFFF8F6),
      secondaryHeaderColor: const Color(0xFFE3F2FD),
      shadowColor: Colors.black,
      splashColor: const Color(0x66C8C8C8),
      splashFactory: InkRipple.splashFactory,
      unselectedWidgetColor: const Color(0x8A000000),
      useMaterial3: false,
      visualDensity: VisualDensity.compact,
    );
  }
}

